apiVersion: v1
kind: Service
metadata:
  name: speedjobs-model-service
  namespace: skala-practice
  labels:
    app: speedjobs-model-service
spec:
  selector:
    app: speedjobs-model-service
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP